name: HOODWINK
favicon: null
layout_spectrum: 0.24159
typography_spectrum: 0.28477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#28467a'
    - '#fcfdf7'
    - '#0c0a0d'
    - '#7a93a9'
    - '#945130'
  brandStrength: 0.5
  lightness: 0.19564282102510333
  saturation: 0.8012845262419432
  rhythmicContrast: 0.6526830706279725
purpose: []
